### ISSUE TITLE
Pruning decision trees

### ISSUE THREAD

**Issue by charlesxjyang** [doubleplusplus/incremental_decision_tree-CART-Random_Forest_python#4]
Would there be any way to implement pre/post pruning of either VFDT/EFDT?

**Comment by doubleplusplus** [comment]
It's possible to prune VFDT, but I am too lazy to implement the pruning. I suppose you can use an ensemble of VFDT, like a Random Forest style to avoid pruning. 

For EFDT, I don't think you need to prune it. Because it's dynamic and can modify itself based on future data instances. Therefore pruning is now necessary.
